from OCP.GccEnt import GccEnt_enclosed, GccEnt_enclosing, GccEnt_outside, GccEnt_unqualified
from enum import Enum, IntEnum
from typing import TypeAlias

class Align(Enum):
    """Align object about Axis"""
    MIN = ...
    CENTER = ...
    MAX = ...
    NONE = None
Align2D: TypeAlias = Align | None | tuple[Align | None, Align | None]
Align3D: TypeAlias = Align | None | tuple[Align | None, Align | None, Align | None]

class ApproxOption(Enum):
    """DXF export spline approximation strategy"""
    ARC = ...
    NONE = ...
    SPLINE = ...

class AngularDirection(Enum):
    """Angular rotation direction"""
    CLOCKWISE = ...
    COUNTER_CLOCKWISE = ...

class CenterOf(Enum):
    """Center Options"""
    GEOMETRY = ...
    MASS = ...
    BOUNDING_BOX = ...

class ContinuityLevel(IntEnum):
    """
    Continuity level for evaluating geometric connections.

    Used to determine how smoothly adjacent geometry joins together,
    such as at shared vertices between edges or shared edges between faces.

    Levels:

    - C0 (G0): Positional continuity—elements meet at a point but may have sharp angles.
    - C1 (G1): Tangent continuity—elements have the same tangent direction at the junction.
    - C2 (G2): Curvature continuity—elements have matching curvature at the junction.

    These levels correspond to common CAD definitions and are compatible with OCCT's GeomAbs_Shape.
    """
    C0 = 0
    C1 = 1
    C2 = 2

class Extrinsic(Enum):
    """Order to apply extrinsic rotations by axis"""
    XYZ = ...
    XZY = ...
    YZX = ...
    YXZ = ...
    ZXY = ...
    ZYX = ...
    XYX = ...
    XZX = ...
    YZY = ...
    YXY = ...
    ZXZ = ...
    ZYZ = ...

class FrameMethod(Enum):
    """Moving frame calculation method"""
    FRENET = ...
    CORRECTED = ...

class GeomType(Enum):
    """CAD geometry object type"""
    PLANE = ...
    CYLINDER = ...
    CONE = ...
    SPHERE = ...
    TORUS = ...
    BEZIER = ...
    BSPLINE = ...
    REVOLUTION = ...
    EXTRUSION = ...
    OFFSET = ...
    LINE = ...
    CIRCLE = ...
    ELLIPSE = ...
    HYPERBOLA = ...
    PARABOLA = ...
    OTHER = ...

class HeadType(Enum):
    """Arrow head types"""
    STRAIGHT = ...
    CURVED = ...
    FILLETED = ...

class Intrinsic(Enum):
    """Order to apply intrinsic rotations by axis"""
    XYZ = ...
    XZY = ...
    YZX = ...
    YXZ = ...
    ZXY = ...
    ZYX = ...
    XYX = ...
    XZX = ...
    YZY = ...
    YXY = ...
    ZXZ = ...
    ZYZ = ...

class Keep(Enum):
    """Split options"""
    ALL = ...
    BOTTOM = ...
    BOTH = ...
    INSIDE = ...
    OUTSIDE = ...
    TOP = ...

class Kind(Enum):
    """Offset corner transition"""
    ARC = ...
    INTERSECTION = ...
    TANGENT = ...

class Mode(Enum):
    """Combination Mode"""
    ADD = ...
    SUBTRACT = ...
    INTERSECT = ...
    REPLACE = ...
    PRIVATE = ...

class FontStyle(Enum):
    """Text Font Styles"""
    REGULAR = ...
    BOLD = ...
    ITALIC = ...
    BOLDITALIC = ...

class Sagitta(Enum):
    """Sagitta selection"""
    SHORT = 0
    LONG = -1
    BOTH = 1

class LengthMode(Enum):
    """Method of specifying length along PolarLine"""
    DIAGONAL = ...
    HORIZONTAL = ...
    VERTICAL = ...

class MeshType(Enum):
    """3MF mesh types typically for 3D printing"""
    OTHER = ...
    MODEL = ...
    SUPPORT = ...
    SOLIDSUPPORT = ...

class NumberDisplay(Enum):
    """Methods for displaying numbers"""
    DECIMAL = ...
    FRACTION = ...

class PageSize(Enum):
    """Align object about Axis"""
    A0 = ...
    A1 = ...
    A2 = ...
    A3 = ...
    A4 = ...
    A5 = ...
    A6 = ...
    A7 = ...
    A8 = ...
    A9 = ...
    A10 = ...
    LETTER = ...
    LEGAL = ...
    LEDGER = ...

class Tangency(Enum):
    """Tangency constraint for solvers edge selection"""
    UNQUALIFIED = GccEnt_unqualified
    ENCLOSING = GccEnt_enclosing
    ENCLOSED = GccEnt_enclosed
    OUTSIDE = GccEnt_outside

class PositionMode(Enum):
    """Position along curve mode"""
    LENGTH = ...
    PARAMETER = ...

class PrecisionMode(Enum):
    """
    When you export a model to a STEP file, the precision of the geometric data
    (such as the coordinates of points, the definitions of curves and surfaces, etc.)
    can significantly impact the file size and the fidelity of the model when it is
    imported into another CAD system. Higher precision means that the geometric
    data is described with more detail, which can improve the accuracy of the model
    in the target system but can also increase the file size.
    """
    SESSION = 2
    GREATEST = 1
    AVERAGE = 0
    LEAST = -1

class Select(Enum):
    """Selector scope - all, last operation or new objects"""
    ALL = ...
    LAST = ...
    NEW = ...

class Side(Enum):
    """2D Offset types"""
    LEFT = ...
    RIGHT = ...
    BOTH = ...

class SortBy(Enum):
    """Sorting criteria"""
    LENGTH = ...
    RADIUS = ...
    AREA = ...
    VOLUME = ...
    DISTANCE = ...

class TextAlign(Enum):
    """Text Alignment"""
    BOTTOM = ...
    CENTER = ...
    LEFT = ...
    RIGHT = ...
    TOP = ...
    TOPFIRSTLINE = ...

class Transition(Enum):
    """Sweep discontinuity handling option"""
    RIGHT = ...
    ROUND = ...
    TRANSFORMED = ...

class Unit(Enum):
    """Standard Units"""
    MC = ...
    MM = ...
    CM = ...
    M = ...
    IN = ...
    FT = ...

class Until(Enum):
    """Extrude limit"""
    NEXT = ...
    LAST = ...
    PREVIOUS = ...
    FIRST = ...
